# Generated by Django 5.2.12 on 2026-04-22 16:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0045_add_content_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMetadataIndexingState',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_indexed_at', models.DateTimeField(blank=True, db_index=True, help_text='When this content was last successfully written to Algolia.', null=True)),
                ('removed_from_index_at', models.DateTimeField(blank=True, db_index=True, help_text='When this content was last removed from Algolia.', null=True)),
                ('algolia_object_ids', models.JSONField(blank=True, default=list, help_text='Algolia object IDs (shards) produced for this content on last index.')),
                ('last_failure_at', models.DateTimeField(blank=True, db_index=True, help_text='When the most recent indexing failure occurred, if any.', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for the most recent indexing failure, if any.', null=True)),
                ('content_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indexing_state', to='catalog.contentmetadata')),
            ],
            options={
                'verbose_name': 'Content Metadata Indexing State',
                'verbose_name_plural': 'Content Metadata Indexing States',
            },
        ),
    ]
