# Generated by Django 5.2.9 on 2026-03-18 19:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0045_add_content_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMetadataIndexingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='When this record was last successfully indexed to Algolia.', null=True)),
                ('removed_from_index_at', models.DateTimeField(blank=True, help_text='When this record was removed from the Algolia index.', null=True)),
                ('algolia_object_ids', models.JSONField(default=list, help_text='List of Algolia object IDs (shards) for this content.')),
                ('last_failure_at', models.DateTimeField(blank=True, help_text='When indexing last failed for this record.', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='The reason for the last indexing failure.', null=True)),
                ('content_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indexing_state', to='catalog.contentmetadata')),
            ],
            options={
                'verbose_name': 'Content Metadata Indexing State',
                'verbose_name_plural': 'Content Metadata Indexing States',
                'indexes': [models.Index(fields=['last_indexed_at'], name='search_cont_last_in_7620ce_idx'), models.Index(fields=['last_failure_at'], name='search_cont_last_fa_b13208_idx')],
            },
        ),
    ]
