# Generated by Django 5.2.13 on 2026-06-15 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalReindexAlgoliaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('force_all', models.BooleanField(default=False, help_text='Reindex all indexable content regardless of staleness. Equivalent to --force-all on the command line.', verbose_name='Force all')),
                ('dry_run', models.BooleanField(default=False, help_text='Log what would be dispatched without issuing any Algolia writes. Equivalent to --dry-run on the command line.', verbose_name='Dry run')),
                ('no_async', models.BooleanField(default=False, help_text='Run the dispatcher synchronously (blocks until complete). Equivalent to --no-async on the command line.', verbose_name='No async')),
                ('index_name', models.CharField(blank=True, default='', help_text='Target Algolia index name. Leave blank to use the command-line value or the default.', max_length=255, verbose_name='Index name')),
                ('replica_index_name', models.CharField(blank=True, default='', help_text='Algolia replica index name. Leave blank to use the command-line value or the default.', max_length=255, verbose_name='Replica index name')),
                ('content_types', models.CharField(blank=True, default='', help_text='Comma-separated subset of content types to reindex: course, program, learnerpathway, video. Leave blank to reindex all types.', max_length=255, verbose_name='Content types')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'verbose_name': 'Incremental Reindex Algolia Config',
                'verbose_name_plural': 'Incremental Reindex Algolia Configs',
            },
        ),
    ]
